export default {
    verGitHub: "Ver en GitHub",
    acercaDe: "Acerca de Asu",
    aplicarAlpha: "Aplicar alpha",
    aplicarColor: "Aplicar color",
    aplicarSecuenciaPosiciones: "Aplicar secuencia de posiciones",
    aplicarTraslacion: "Aplicar traslación",
    copiar: "Copiar",
    copiarMovimiento: "Copiar movimiento",
    dividirKaraoke: "Dividir karaoke",
    dividirSilabas: "Dividir sílabas",
    lineasCopiadas: "¡Líneas copiadas al portapapeles!",
    resultado: "Resultado",
    subtitulos: "Subtítulos",
    visualizarDialogos: "Visualizar diálogos",
    validarDialogos: "Validar diálogos",
    validateWithGemini: "Validar con Google Gemini",
    validateLineStyleExists: "Validar que los estilos existan",
    validateTextStart: "Validar inicio de los textos",
    validateTextEnd: "Validar fin de los textos",
    validateTextSpaces: "Validar espacios múltiples",
    validateTextPunctuation: "Validar puntuación",
};
