export default {
    verGitHub: "Ver en GitHub",
    acercaDe: "Acerca de Asu",
    aplicarAlpha: "Aplicar alpha",
    aplicarColor: "Aplicar color",
    aplicarSecuenciaPosiciones: "Aplicar secuencia de posiciones",
    copiar: "Copiar",
    copiarMovimiento: "Copiar movimiento",
    dividirKaraoke: "Dividir karaoke",
    dividirSilabas: "Dividir sílabas",
    lineasCopiadas: "¡Líneas copiadas al portapapeles!",
    resultado: "Resultado",
    subtitulos: "Subtítulos",
    validarDialogos: "Validar diálogos",
};
